apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-monitoring-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: log-monitoring-service
  template:
    metadata:
      labels:
        app: log-monitoring-service
    spec:
      containers:
      - name: log-monitoring-service
        image: your-docker-repo/log-monitoring-service:latest
        ports:
        - containerPort: 8080
        - containerPort: 50051
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: log-monitoring-secret
              key: database_url
